// Generated by ReScript, PLEASE EDIT WITH CARE


async function $$default(request) {
  return {
          body: "{\"foo\": \"bar\"}"
        };
}

export {
  $$default ,
  $$default as default,
}
/* No side effect */
