// Generated by ReScript, PLEASE EDIT WITH CARE


async function handler(request) {
  return {
          statusCode: 200,
          body: JSON.stringify(request.body)
        };
}

export {
  handler ,
}
/* No side effect */
